preload = ~/Downloads/Wallpapers/aurora.png
preload = ~/Downloads/Wallpapers/deep-indigo.png
preload = ~/Downloads/Wallpapers/psky.png
preload = ~/Downloads/Wallpapers/starfall1.png
preload = ~/Downloads/Wallpapers/starfall2.png
preload = ~/Downloads/Wallpapers/space-umbra.png
preload = ~/Downloads/Wallpapers/synth.jpg

wallpaper {
    monitor = eDP-1
    path = ~/Downloads/Wallpapers/space-umbra.png
    fit_mode = cover 
}

splash = false
